from __future__ import annotations

import argparse

from .common import add_profile_args
from .foundation import handle_approval, handle_gate, handle_policy, handle_post_runtime, handle_pre_runtime, handle_proof, handle_replay, handle_review, handle_run_alias, handle_runtime, handle_session


def register_foundation_commands(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    pre = subparsers.add_parser("pre-runtime", help="Scan environment, target, agent config, MCP, and Skills.")
    pre.set_defaults(handler=handle_pre_runtime)
    pre.add_argument("--target", default=".", help="Runtime target directory to scan.")
    pre.add_argument("--no-home", action="store_true", help="Do not inspect user-level agent config.")
    pre.add_argument("--output", choices=("json", "text"), default="json")
    pre.add_argument("--save", action="store_true", help="Persist the preflight baseline for later session/proof reference.")
    pre.add_argument("--preflight", default=None, help="Path to write the preflight baseline when --save is used.")

    session = subparsers.add_parser("session", help="Managed session helpers.")
    session.set_defaults(handler=handle_session)
    session_sub = session.add_subparsers(dest="session_command", required=True)
    session_start = session_sub.add_parser("start", help="Start a managed session and create a ledger.")
    session_start.add_argument("--target", default=".")
    session_start.add_argument("--agent", default=None)
    session_start.add_argument("--goal", default=None)
    session_start.add_argument("--session-id", default=None)
    session_start.add_argument("--ledger", default=None)
    session_start.add_argument("--preflight", default=None)
    session_start.add_argument("--no-preflight", action="store_true")
    session_run = session_sub.add_parser("run", help="Start a session, run a child command, and close the session.")
    session_run.add_argument("--target", default=".")
    session_run.add_argument("--agent", default=None)
    session_run.add_argument("--goal", default=None)
    session_run.add_argument("--session-id", default=None)
    session_run.add_argument("--ledger", default=None)
    session_run.add_argument("--preflight", default=None)
    session_run.add_argument("--no-preflight", action="store_true")
    session_run.add_argument("cmd", nargs=argparse.REMAINDER)
    session_close = session_sub.add_parser("close", help="Close a managed session ledger.")
    session_close.add_argument("--ledger", required=True)
    session_close.add_argument("--status", choices=("closed", "aborted"), default="closed")

    run = subparsers.add_parser("run", help="Alias for session run: start a managed session, run a child command, and close it.")
    run.set_defaults(handler=handle_run_alias)
    run.add_argument("--target", default=".")
    run.add_argument("--agent", default=None)
    run.add_argument("--goal", default=None)
    run.add_argument("--session-id", default=None)
    run.add_argument("--ledger", default=None)
    run.add_argument("--preflight", default=None)
    run.add_argument("--no-preflight", action="store_true")
    run.add_argument("cmd", nargs=argparse.REMAINDER)

    runtime = subparsers.add_parser("runtime", help="Runtime audit helpers.")
    runtime.set_defaults(handler=handle_runtime)
    runtime_sub = runtime.add_subparsers(dest="runtime_command", required=True)
    analyze = runtime_sub.add_parser("analyze-event", help="Analyze a runtime event JSON payload.")
    analyze.add_argument("--event", required=True, help="JSON event payload.")
    analyze.add_argument("--session", default=None)
    analyze.add_argument("--ledger", default=None)
    analyze.add_argument("--review", choices=("off", "auto", "always", "required"), default="auto")
    analyze.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    analyze.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    analyze.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(analyze)
    record = runtime_sub.add_parser("record-event", help="Append a runtime event to a v0.1 ledger.")
    record.add_argument("--event", required=True, help="JSON event payload.")
    record.add_argument("--session", default=None)
    record.add_argument("--ledger", "--log", default=".kappaski/session.jsonl", help="JSONL ledger path.")
    record.add_argument("--review", choices=("off", "auto", "always", "required"), default="auto")
    record.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    record.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    record.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(record)
    shell = runtime_sub.add_parser("shell", help="Run a shell command with audit logging and policy decisions.")
    shell.add_argument("--session", default=None)
    shell.add_argument("--ledger", "--log", default=".kappaski/session.jsonl", help="JSONL ledger path.")
    shell.add_argument("--agent", default=None)
    shell.add_argument("--target", default=None)
    shell.add_argument("--review", choices=("off", "auto", "always", "required"), default="auto")
    shell.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    shell.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    shell.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(shell)
    shell.add_argument("cmd", nargs=argparse.REMAINDER, help="Command to run after --.")
    approve = runtime_sub.add_parser("approve", help="Record approval evidence for a policy decision.")
    approve.add_argument("--ledger", required=True)
    approve.add_argument("--decision", required=True)
    approve.add_argument("--approver", default=None)
    approve.add_argument("--reason", default=None)
    reject = runtime_sub.add_parser("reject", help="Record rejection evidence for a policy decision.")
    reject.add_argument("--ledger", required=True)
    reject.add_argument("--decision", required=True)
    reject.add_argument("--approver", default=None)
    reject.add_argument("--reason", default=None)
    outcome = runtime_sub.add_parser("outcome", help="Record the observed execution outcome for a decision or invocation.")
    outcome.add_argument("--ledger", required=True)
    outcome.add_argument("--decision", default=None)
    outcome.add_argument("--invocation", default=None)
    outcome.add_argument("--status", choices=("executed", "blocked", "skipped", "overridden", "failed"), required=True)
    outcome.add_argument("--actor", default=None)
    outcome.add_argument("--reason", default=None)

    approval = subparsers.add_parser("approval", help="List and resolve approval inbox items.")
    approval.set_defaults(handler=handle_approval)
    approval_sub = approval.add_subparsers(dest="approval_command", required=True)
    approval_list = approval_sub.add_parser("list", help="List approval items from a ledger.")
    approval_list.add_argument("--ledger", required=True)
    approval_list.add_argument("--status", default=None)
    approval_approve = approval_sub.add_parser("approve", help="Approve one decision or all missing approvals.")
    approval_approve.add_argument("--ledger", required=True)
    approval_approve.add_argument("--decision", default=None)
    approval_approve.add_argument("--all", action="store_true")
    approval_approve.add_argument("--approver", default=None)
    approval_approve.add_argument("--reason", default=None)
    approval_reject = approval_sub.add_parser("reject", help="Reject one decision or all missing approvals.")
    approval_reject.add_argument("--ledger", required=True)
    approval_reject.add_argument("--decision", default=None)
    approval_reject.add_argument("--all", action="store_true")
    approval_reject.add_argument("--approver", default=None)
    approval_reject.add_argument("--reason", default=None)

    replay = subparsers.add_parser("replay", help="Export runtime replay reports.")
    replay.set_defaults(handler=handle_replay)
    replay_sub = replay.add_subparsers(dest="replay_command", required=True)
    replay_export = replay_sub.add_parser("export", help="Export a static HTML replay report.")
    replay_export.add_argument("--ledger", required=True)
    replay_export.add_argument("--out", required=True)
    replay_export.add_argument("--gate-mode", choices=("audit", "managed", "ci"), default="managed")
    replay_export.add_argument("--case", default=None)
    replay_export.add_argument("--no-raw", action="store_true")
    add_profile_args(replay_export)

    policy = subparsers.add_parser("policy", help="Inspect policy decisions and merged evaluations.")
    policy.set_defaults(handler=handle_policy)
    policy_sub = policy.add_subparsers(dest="policy_command", required=True)
    policy_validate = policy_sub.add_parser("validate", help="Validate a Kappaski-native policy-as-code profile.")
    policy_validate.add_argument("--profile", required=True)
    policy_test = policy_sub.add_parser("test", help="Run built-in product tests against a policy-as-code profile.")
    policy_test.add_argument("--profile", required=True)
    policy_explain = policy_sub.add_parser("explain", help="Explain a policy decision from the ledger.")
    policy_explain.add_argument("--ledger", required=True)
    policy_explain.add_argument("--decision", default=None)
    policy_explain.add_argument("--invocation", default=None)
    policy_check_path = policy_sub.add_parser("check-path", help="Evaluate path-aware policy over a ledger.")
    policy_check_path.add_argument("--ledger", required=True)
    policy_check_path.add_argument("--profile", default=None)
    policy_check_path.add_argument("--out", default=None)

    review = subparsers.add_parser("review", help="Inspect semantic review records.")
    review.set_defaults(handler=handle_review)
    review_sub = review.add_subparsers(dest="review_command", required=True)
    review_invocation = review_sub.add_parser("invocation", help="Show semantic review output for an invocation.")
    review_invocation.add_argument("--ledger", required=True)
    review_invocation.add_argument("--invocation", required=True)
    review_invocation.add_argument("--review", default=None)

    gate = subparsers.add_parser("gate", help="Consume proof and ledger artifacts as release/CI gates.")
    gate.set_defaults(handler=handle_gate)
    gate_sub = gate.add_subparsers(dest="gate_command", required=True)
    gate_verify = gate_sub.add_parser("verify", help="Evaluate proof/ledger artifacts against a gate mode.")
    gate_verify.add_argument("--proof", default=None)
    gate_verify.add_argument("--ledger", default=None)
    gate_verify.add_argument("--mode", choices=("audit", "managed", "ci"), default="managed")
    gate_verify.add_argument("--out", default=None)
    add_profile_args(gate_verify)

    proof = subparsers.add_parser("proof", help="Export or verify proof reports.")
    proof.set_defaults(handler=handle_proof)
    proof_sub = proof.add_subparsers(dest="proof_command", required=True)
    proof_export = proof_sub.add_parser("export", help="Export a proof JSON report.")
    proof_export.add_argument("--ledger", "--events", default=".kappaski/session.jsonl")
    proof_export.add_argument("--out", "--output", default=None)
    proof_verify = proof_sub.add_parser("verify", help="Verify a proof, a ledger, or both.")
    proof_verify.add_argument("--proof", default=None)
    proof_verify.add_argument("--ledger", "--events", default=None)

    post = subparsers.add_parser("post-runtime", help="Summarize a JSONL runtime audit log.")
    post.set_defaults(handler=handle_post_runtime)
    post.add_argument("--events", default=".kappaski/session.jsonl", help="JSONL event log path.")

