from __future__ import annotations

import argparse

from ..harness import SWE_BENCH_FULL_DATASET, SWE_BENCH_FULL_EXPECTED_INSTANCES, SWE_BENCH_LITE_DATASET
from .common import add_profile_args
from .foundation import handle_approval, handle_gate, handle_policy, handle_post_runtime, handle_pre_runtime, handle_proof, handle_replay, handle_review, handle_run_alias, handle_runtime, handle_session
from .governance import handle_corpus, handle_daemon, handle_identity, handle_profile, handle_teamrun
from .integrations import handle_adapter, handle_bridge, handle_coverage, handle_enforce, handle_external_validation, handle_graph, handle_harness, handle_mcp, handle_mediation, handle_native, handle_supervise
from .product import handle_audit, handle_demo, handle_eval, handle_evidence, handle_experiment, handle_release_candidate, handle_roadmap


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="kappaski", description="AI coding agent runtime proof prototype.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    corpus = subparsers.add_parser("corpus", help="Inspect pinned real-world Skill/tool corpora.")
    corpus.set_defaults(handler=handle_corpus)
    corpus_sub = corpus.add_subparsers(dest="corpus_command", required=True)
    corpus_scan = corpus_sub.add_parser("scan", help="Scan pinned real corpus snapshots for capability and risk surface.")
    corpus_scan.add_argument("--root", default="benchmarks/corpora")

    identity = subparsers.add_parser("identity", help="Declare principals, bind agent identity, and inspect accountability facts.")
    identity.set_defaults(handler=handle_identity)
    identity_sub = identity.add_subparsers(dest="identity_command", required=True)
    identity_declare = identity_sub.add_parser("declare", help="Declare a local principal.")
    identity_declare.add_argument("--principal", required=True)
    identity_declare.add_argument("--display-name", default=None)
    identity_declare.add_argument("--source", default="local")
    identity_declare.add_argument("--out", default=None)
    identity_bind = identity_sub.add_parser("bind", help="Append principal, agent, credential, and grant facts to a ledger.")
    identity_bind.add_argument("--ledger", required=True)
    identity_bind.add_argument("--session", required=True)
    identity_bind.add_argument("--principal", required=True)
    identity_bind.add_argument("--agent", required=True)
    identity_bind.add_argument("--adapter-agent", default=None)
    identity_bind.add_argument("--scope", action="append", default=[])
    identity_bind.add_argument("--resource", action="append", default=[])
    identity_bind.add_argument("--env-key", action="append", default=[])
    identity_inspect = identity_sub.add_parser("inspect", help="Inspect accountability facts from a ledger.")
    identity_inspect.add_argument("--ledger", required=True)

    daemon = subparsers.add_parser("daemon", help="Runtime authority and session registry commands.")
    daemon.set_defaults(handler=handle_daemon)
    daemon_sub = daemon.add_subparsers(dest="daemon_command", required=True)
    daemon_init = daemon_sub.add_parser("init", help="Initialize the local runtime authority registry.")
    daemon_init.add_argument("--target", default=".")
    daemon_status = daemon_sub.add_parser("status", help="Show local runtime authority status.")
    daemon_status.add_argument("--target", default=".")
    daemon_record = daemon_sub.add_parser("record-event", help="Record a runtime event through the authority.")
    daemon_record.add_argument("--target", default=".")
    daemon_record.add_argument("--session", required=True)
    daemon_record.add_argument("--event", required=True)
    daemon_record.add_argument("--review", choices=("off", "auto", "always", "required"), default="auto")
    daemon_record.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    daemon_record.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    daemon_record.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(daemon_record)
    daemon_heartbeat = daemon_sub.add_parser("heartbeat", help="Update session heartbeat metadata.")
    daemon_heartbeat.add_argument("--target", default=".")
    daemon_heartbeat.add_argument("--session", required=True)
    daemon_heartbeat.add_argument("--actor", default=None)
    daemon_register = daemon_sub.add_parser("register-capabilities", help="Register scanned adapter/skill capabilities into a session ledger.")
    daemon_register.add_argument("--target", default=".")
    daemon_register.add_argument("--session", required=True)
    daemon_register.add_argument("--corpus-root", default="benchmarks/corpora")
    daemon_register.add_argument("--adapter", default="unknown")
    daemon_register.add_argument("--review", choices=("off", "auto", "always", "required"), default="off")
    daemon_register.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="managed")
    daemon_register.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    daemon_register.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(daemon_register)
    daemon_approve = daemon_sub.add_parser("approve", help="Resolve a pending approval through the authority.")
    daemon_approve.add_argument("--target", default=".")
    daemon_approve.add_argument("--session", required=True)
    daemon_approve.add_argument("--decision", required=True)
    daemon_approve.add_argument("--approver", default=None)
    daemon_approve.add_argument("--reason", default=None)
    daemon_reject = daemon_sub.add_parser("reject", help="Reject a pending approval through the authority.")
    daemon_reject.add_argument("--target", default=".")
    daemon_reject.add_argument("--session", required=True)
    daemon_reject.add_argument("--decision", required=True)
    daemon_reject.add_argument("--approver", default=None)
    daemon_reject.add_argument("--reason", default=None)
    daemon_outcome = daemon_sub.add_parser("outcome", help="Record execution outcome through the authority.")
    daemon_outcome.add_argument("--target", default=".")
    daemon_outcome.add_argument("--session", required=True)
    daemon_outcome.add_argument("--decision", default=None)
    daemon_outcome.add_argument("--invocation", default=None)
    daemon_outcome.add_argument("--status", choices=("executed", "blocked", "skipped", "overridden", "failed"), required=True)
    daemon_outcome.add_argument("--actor", default=None)
    daemon_outcome.add_argument("--reason", default=None)
    daemon_session = daemon_sub.add_parser("session", help="Manage authority sessions.")
    daemon_session_sub = daemon_session.add_subparsers(dest="daemon_session_command", required=True)
    daemon_session_create = daemon_session_sub.add_parser("create", help="Create and register a managed session.")
    daemon_session_create.add_argument("--target", default=".")
    daemon_session_create.add_argument("--agent", default=None)
    daemon_session_create.add_argument("--goal", default=None)
    daemon_session_create.add_argument("--session-id", default=None)
    daemon_session_create.add_argument("--ledger", default=None)
    daemon_session_create.add_argument("--preflight", default=None)
    daemon_session_create.add_argument("--no-preflight", action="store_true")
    add_profile_args(daemon_session_create)
    daemon_session_list = daemon_session_sub.add_parser("list", help="List registered sessions.")
    daemon_session_list.add_argument("--target", default=".")
    daemon_session_list.add_argument("--include-deleted", action="store_true")
    daemon_session_show = daemon_session_sub.add_parser("show", help="Show a registered session.")
    daemon_session_show.add_argument("--target", default=".")
    daemon_session_show.add_argument("--session", required=True)
    for _name in ("pause", "resume", "interrupt", "stop", "delete"):
        _parser = daemon_session_sub.add_parser(_name, help=f"{_name.capitalize()} a registered session.")
        _parser.add_argument("--target", default=".")
        _parser.add_argument("--session", required=True)
        _parser.add_argument("--reason", default=None)

    pre = subparsers.add_parser("pre-runtime", help="Scan environment, target, agent config, MCP, and Skills.")
    pre.set_defaults(handler=handle_pre_runtime)
    pre.add_argument("--target", default=".", help="Runtime target directory to scan.")
    pre.add_argument("--no-home", action="store_true", help="Do not inspect user-level agent config.")
    pre.add_argument("--output", choices=("json", "text"), default="json")
    pre.add_argument("--save", action="store_true", help="Persist the preflight baseline for later session/proof reference.")
    pre.add_argument("--preflight", default=None, help="Path to write the preflight baseline when --save is used.")

    session = subparsers.add_parser("session", help="Managed session helpers.")
    session.set_defaults(handler=handle_session)
    session_sub = session.add_subparsers(dest="session_command", required=True)
    session_start = session_sub.add_parser("start", help="Start a managed session and create a ledger.")
    session_start.add_argument("--target", default=".")
    session_start.add_argument("--agent", default=None)
    session_start.add_argument("--goal", default=None)
    session_start.add_argument("--session-id", default=None)
    session_start.add_argument("--ledger", default=None)
    session_start.add_argument("--preflight", default=None)
    session_start.add_argument("--no-preflight", action="store_true")
    session_run = session_sub.add_parser("run", help="Start a session, run a child command, and close the session.")
    session_run.add_argument("--target", default=".")
    session_run.add_argument("--agent", default=None)
    session_run.add_argument("--goal", default=None)
    session_run.add_argument("--session-id", default=None)
    session_run.add_argument("--ledger", default=None)
    session_run.add_argument("--preflight", default=None)
    session_run.add_argument("--no-preflight", action="store_true")
    session_run.add_argument("cmd", nargs=argparse.REMAINDER)
    session_close = session_sub.add_parser("close", help="Close a managed session ledger.")
    session_close.add_argument("--ledger", required=True)
    session_close.add_argument("--status", choices=("closed", "aborted"), default="closed")

    run = subparsers.add_parser("run", help="Alias for session run: start a managed session, run a child command, and close it.")
    run.set_defaults(handler=handle_run_alias)
    run.add_argument("--target", default=".")
    run.add_argument("--agent", default=None)
    run.add_argument("--goal", default=None)
    run.add_argument("--session-id", default=None)
    run.add_argument("--ledger", default=None)
    run.add_argument("--preflight", default=None)
    run.add_argument("--no-preflight", action="store_true")
    run.add_argument("cmd", nargs=argparse.REMAINDER)

    adapter = subparsers.add_parser("adapter", help="Reference adapter wrapper workflows.")
    adapter.set_defaults(handler=handle_adapter)
    adapter_sub = adapter.add_subparsers(dest="adapter_command", required=True)
    adapter_run = adapter_sub.add_parser("run", help="Run a child command through a Kappaski reference adapter wrapper.")
    adapter_run.add_argument("--target", default=".")
    adapter_run.add_argument("--agent", default=None)
    adapter_run.add_argument("--goal", default=None)
    adapter_run.add_argument("--session-id", default=None)
    adapter_run.add_argument("--out-dir", default=None)
    adapter_run.add_argument("--corpus-root", default="benchmarks/corpora")
    adapter_run.add_argument("--capabilities", choices=("off", "audit", "managed"), default="audit")
    adapter_run.add_argument("--gate", choices=("off", "audit", "managed", "ci"), default="off")
    adapter_run.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    adapter_run.add_argument("--enforcement", choices=("off", "file-write"), default="off")
    adapter_run.add_argument("--no-preflight", action="store_true")
    adapter_run.add_argument("cmd", nargs=argparse.REMAINDER)
    adapter_inspect = adapter_sub.add_parser("inspect", help="Inspect and verify an adapter runtime package manifest.")
    adapter_inspect.add_argument("--package", required=True)
    adapter_package = adapter_sub.add_parser("package", help="Package an existing adapter ledger into an evidence bundle.")
    adapter_package.add_argument("--ledger", required=True)
    adapter_package.add_argument("--out-dir", required=True)
    adapter_profile = adapter_sub.add_parser("profile", help="Inspect a hardened adapter profile.")
    adapter_profile.add_argument("--kind", choices=("claude-code", "codex", "generic"), default="claude-code")
    adapter_claude_check = adapter_sub.add_parser("claude-code-check", help="Check a real Claude Code binary environment when available.")
    adapter_claude_check.add_argument("--binary", default="claude")
    adapter_claude = adapter_sub.add_parser("claude-code", help="Run a command through the Claude Code wrapper/hook bridge.")
    adapter_claude.add_argument("--target", default=".")
    adapter_claude.add_argument("--out-dir", default=None)
    adapter_claude.add_argument("--hook-events", default=None)
    adapter_claude.add_argument("--session-id", default=None)
    adapter_claude.add_argument("--no-preflight", action="store_true")
    adapter_claude.add_argument("--enforcement", choices=("off", "file-write"), default="off")
    adapter_claude.add_argument("cmd", nargs=argparse.REMAINDER)

    harness = subparsers.add_parser("harness", help="Compare real agent harness compatibility artifacts.")
    harness.set_defaults(handler=handle_harness)
    harness_sub = harness.add_subparsers(dest="harness_command", required=True)
    harness_compare = harness_sub.add_parser("compare", help="Compare baseline and Kappaski-wrapped harness artifacts.")
    harness_compare.add_argument("--baseline", required=True)
    harness_compare.add_argument("--wrapped", required=True)
    harness_compare.add_argument("--case", default=None)
    harness_swe = harness_sub.add_parser("swe-bench-lite", help="Run or compare optional SWE-Bench Lite harness artifacts.")
    harness_swe.add_argument("--case", required=True)
    harness_swe.add_argument("--baseline-artifact", default=None)
    harness_swe.add_argument("--wrapped-artifact", default=None)
    harness_swe.add_argument("--out", default=None)
    harness_swe.add_argument("--dependency", default="docker")
    harness_swe.add_argument("--skip-if-unavailable", action="store_true")
    harness_swe.add_argument("--baseline-command", default=None, help="Command that produces the baseline artifact as its last argument.")
    harness_swe.add_argument("--wrapped-command", default=None, help="Command that produces the Kappaski-wrapped artifact as its last argument.")
    harness_official = harness_sub.add_parser("swe-bench-official", help="Run the official SWE-Bench Lite harness entrypoint when installed.")
    harness_official.add_argument("--python", default="python")
    harness_official.add_argument("--dataset-name", default=SWE_BENCH_LITE_DATASET)
    harness_official.add_argument("--split", default="test")
    harness_official.add_argument("--instance-id", action="append", default=[])
    harness_official.add_argument("--predictions-path", default="gold")
    harness_official.add_argument("--run-id", default="kappaski_smoke")
    harness_official.add_argument("--report-dir", default=None)
    harness_official.add_argument("--timeout", type=int, default=60)
    harness_official.add_argument("--max-workers", type=int, default=1)
    harness_official.add_argument("--cache-level", default="instance")
    harness_official.add_argument("--clean", action="store_true")
    harness_official.add_argument("--work-dir", default=None)
    harness_official.add_argument("--out", default=None)
    harness_official.add_argument("--command", dest="override_command", default=None, help="Override command for test or custom harness use.")
    harness_official.add_argument("--report-path", default=None, help="Explicit official report JSON path for command override.")
    harness_managed = harness_sub.add_parser("managed-check", help="Run a command through managed harness pause/approval/resume compatibility flow.")
    harness_managed.add_argument("--target", default=".")
    harness_managed.add_argument("--case", default=None)
    harness_managed.add_argument("--approval-actor", default="human-approver")
    harness_managed.add_argument("cmd", nargs=argparse.REMAINDER)

    external_validation = subparsers.add_parser("external-validation", help="Run explicit optional upstream/live benchmark validation.")
    external_validation.set_defaults(handler=handle_external_validation)
    external_validation_sub = external_validation.add_subparsers(dest="external_validation_command", required=True)
    swe_full = external_validation_sub.add_parser("swe-bench-full", help="Run and validate the official full SWE-Bench evaluation chain.")
    swe_full.add_argument("--python", default="python")
    swe_full.add_argument("--dataset-name", default=SWE_BENCH_FULL_DATASET)
    swe_full.add_argument("--split", default="test")
    swe_full.add_argument("--predictions-path", default="gold")
    swe_full.add_argument("--run-id", default="kappaski_swe_bench_full")
    swe_full.add_argument("--report-dir", default=None)
    swe_full.add_argument("--timeout", type=int, default=1800)
    swe_full.add_argument("--max-workers", type=int, default=1)
    swe_full.add_argument("--cache-level", default="instance")
    swe_full.add_argument("--clean", action="store_true")
    swe_full.add_argument("--work-dir", default=None)
    swe_full.add_argument("--out", default=None)
    swe_full.add_argument("--command", dest="override_command", default=None, help="Override command for contract tests or custom official harness use.")
    swe_full.add_argument("--report-path", default=None, help="Explicit official report JSON path.")
    swe_full.add_argument("--instance-results-path", default=None, help="Explicit official instance_results.jsonl path.")
    swe_full.add_argument("--expected-total-instances", type=int, default=SWE_BENCH_FULL_EXPECTED_INSTANCES)
    swe_full.add_argument("--allow-subset", action="store_true", help="Mark this as a subset smoke run; it will not satisfy full external validation.")

    profile = subparsers.add_parser("profile", help="Resolve TOML/JSON policy profiles with session > repo > team precedence.")
    profile.set_defaults(handler=handle_profile)
    profile_sub = profile.add_subparsers(dest="profile_command", required=True)
    profile_resolve = profile_sub.add_parser("resolve", help="Resolve policy profile precedence.")
    profile_resolve.add_argument("--team", default=None)
    profile_resolve.add_argument("--repo", default=None)
    profile_resolve.add_argument("--session", default=None)
    profile_break_glass = profile_sub.add_parser("break-glass", help="Record a ledger-backed break-glass override.")
    profile_break_glass.add_argument("--ledger", required=True)
    profile_break_glass.add_argument("--session", required=True)
    profile_break_glass.add_argument("--actor", required=True)
    profile_break_glass.add_argument("--reason", required=True)
    profile_break_glass.add_argument("--scope", required=True)
    profile_break_glass.add_argument("--expires-at", default=None)
    profile_distribute = profile_sub.add_parser("distribute", help="Create a signed profile distribution bundle.")
    profile_distribute.add_argument("--profile", required=True)
    profile_distribute.add_argument("--scope", choices=("team", "repo", "session"), required=True)
    profile_distribute.add_argument("--distributed-by", required=True)
    profile_review = profile_sub.add_parser("review-override", help="Record administrator/auditor review of a break-glass override.")
    profile_review.add_argument("--ledger", required=True)
    profile_review.add_argument("--override", required=True)
    profile_review.add_argument("--reviewer", required=True)
    profile_review.add_argument("--status", choices=("approved", "rejected"), required=True)
    profile_review.add_argument("--reason", required=True)
    profile_registry = profile_sub.add_parser("registry", help="Create an enterprise profile registry from inline profile JSON.")
    profile_registry.add_argument("--owner", required=True)
    profile_registry.add_argument("--profile", action="append", required=True)
    profile_pin = profile_sub.add_parser("pin", help="Pin a profile from a registry JSON file.")
    profile_pin.add_argument("--registry", required=True)
    profile_pin.add_argument("--scope", choices=("team", "repo", "session"), required=True)
    profile_pin.add_argument("--name", required=True)
    profile_pin.add_argument("--distributed-by", required=True)
    profile_pin.add_argument("--out", default=None)
    profile_verify = profile_sub.add_parser("verify", help="Verify a pinned profile bundle against a registry.")
    profile_verify.add_argument("--registry", required=True)
    profile_verify.add_argument("--bundle", required=True)

    teamrun = subparsers.add_parser("teamrun", help="Create and inspect multi-user TeamRun and Handoff records.")
    teamrun.set_defaults(handler=handle_teamrun)
    teamrun_sub = teamrun.add_subparsers(dest="teamrun_command", required=True)
    teamrun_create = teamrun_sub.add_parser("create", help="Create a TeamRun record.")
    teamrun_create.add_argument("--ledger", default=None)
    teamrun_create.add_argument("--name", required=True)
    teamrun_create.add_argument("--user", action="append", default=[])
    teamrun_identity = teamrun_sub.add_parser("identity", help="Declare and validate agent identity.")
    teamrun_identity.add_argument("--ledger", default=None)
    teamrun_identity.add_argument("--agent", required=True)
    teamrun_identity.add_argument("--declared-by", required=True)
    teamrun_identity.add_argument("--adapter-agent", default=None)
    teamrun_handoff = teamrun_sub.add_parser("handoff", help="Create a Handoff record.")
    teamrun_handoff.add_argument("--ledger", default=None)
    teamrun_handoff.add_argument("--source-agent", required=True)
    teamrun_handoff.add_argument("--target-agent", required=True)
    teamrun_handoff.add_argument("--resource", action="append", default=[])
    teamrun_handoff.add_argument("--taint-mode", choices=("resource-reference", "session-wide"), default="resource-reference")
    teamrun_handoff.add_argument("--session-tainted", action="store_true")
    teamrun_blackboard = teamrun_sub.add_parser("blackboard", help="Record a TeamRun blackboard entry.")
    teamrun_blackboard.add_argument("--ledger", required=True)
    teamrun_blackboard.add_argument("--teamrun", required=True)
    teamrun_blackboard.add_argument("--author", required=True)
    teamrun_blackboard.add_argument("--content", required=True)
    teamrun_blackboard.add_argument("--resource", action="append", default=[])
    teamrun_delegate = teamrun_sub.add_parser("delegate-grant", help="Record a restrict-only grant delegation.")
    teamrun_delegate.add_argument("--ledger", required=True)
    teamrun_delegate.add_argument("--source-agent", required=True)
    teamrun_delegate.add_argument("--target-agent", required=True)
    teamrun_delegate.add_argument("--parent-scope", required=True)
    teamrun_delegate.add_argument("--delegate-scope", required=True)
    teamrun_proof = teamrun_sub.add_parser("proof", help="Export TeamRun proof facts from a ledger.")
    teamrun_proof.add_argument("--ledger", required=True)
    teamrun_proof.add_argument("--out", default=None)
    teamrun_aggregate = teamrun_sub.add_parser("aggregate", help="Aggregate TeamRun proof facts across multiple ledgers.")
    teamrun_aggregate.add_argument("--ledger", action="append", required=True)
    teamrun_aggregate.add_argument("--out", default=None)
    teamrun_timeline = teamrun_sub.add_parser("timeline", help="Export a multi-ledger TeamRun timeline HTML report.")
    teamrun_timeline.add_argument("--ledger", action="append", required=True)
    teamrun_timeline.add_argument("--out", required=True)

    enforce = subparsers.add_parser("enforce", help="Evaluate enforcement guard decisions.")
    enforce.set_defaults(handler=handle_enforce)
    enforce_sub = enforce.add_subparsers(dest="enforce_command", required=True)
    enforce_check = enforce_sub.add_parser("check", help="Check an event against an enforcement domain.")
    enforce_check.add_argument("--event", required=True)
    enforce_check.add_argument("--domain", choices=("file-write", "env-secrets", "network-egress"), default="file-write")
    add_profile_args(enforce_check)
    enforce_shim_spec = enforce_sub.add_parser("shim-spec", help="Show Rust shim contract and source availability.")
    enforce_shim_spec.add_argument("--domain", choices=("file-write",), default="file-write")
    enforce_build = enforce_sub.add_parser("rust-build-check", help="Run cargo check for the Rust shim when cargo is available.")
    enforce_build.add_argument("--skip-if-unavailable", action="store_true")
    enforce_shim_decision = enforce_sub.add_parser("shim-decision", help="Evaluate an event with the compiled Rust shim.")
    enforce_shim_decision.add_argument("--event", required=True)
    enforce_shim_decision.add_argument("--crate", default=None)
    enforce_run = enforce_sub.add_parser("run-file-write", help="Run a command through the Rust file-write shim before execution.")
    enforce_run.add_argument("--ledger", default=None)
    enforce_run.add_argument("--session", default=None)
    enforce_run.add_argument("--target", default=None)
    enforce_run.add_argument("--allow-approval-required", action="store_true", help="Execute require_approval commands in open/audit-style mode.")
    enforce_run.add_argument("--crate", default=None)
    enforce_run.add_argument("cmd", nargs=argparse.REMAINDER)
    enforce_run_domain = enforce_sub.add_parser("run", help="Run a command through a selected enforcement domain before execution.")
    enforce_run_domain.add_argument("--domain", choices=("file-write", "env-secrets", "network-egress"), required=True)
    enforce_run_domain.add_argument("--event", default=None)
    enforce_run_domain.add_argument("--ledger", default=None)
    enforce_run_domain.add_argument("--session", default=None)
    enforce_run_domain.add_argument("--target", default=None)
    enforce_run_domain.add_argument("--allow-approval-required", action="store_true")
    enforce_run_domain.add_argument("cmd", nargs=argparse.REMAINDER)

    native = subparsers.add_parser("native", help="Inspect and manage native agent integration surfaces.")
    native.set_defaults(handler=handle_native)
    native_sub = native.add_subparsers(dest="native_command", required=True)
    native_inventory = native_sub.add_parser("inventory", help="Inventory hooks, plugins, extensions, rules, MCP, sandbox, and config surfaces.")
    native_inventory.add_argument("--target", default=".")
    native_inventory.add_argument("--include-global-config", action="store_true")
    native_install = native_sub.add_parser("install", help="Preview or install native Kappaski hook/plugin config.")
    native_install.add_argument("--target", default=".")
    native_install.add_argument("--agent", choices=("claude-code", "codex", "opencode"), required=True)
    native_install.add_argument("--confirm", action="store_true")
    native_conformance = native_sub.add_parser("conformance", help="Hash and validate discovered native integration surfaces.")
    native_conformance.add_argument("--target", default=".")
    native_conformance.add_argument("--include-global-config", action="store_true")

    bridge = subparsers.add_parser("bridge", help="Native hook/plugin bridge commands.")
    bridge.set_defaults(handler=handle_bridge)
    bridge_sub = bridge.add_subparsers(dest="bridge_command", required=True)
    bridge_native = bridge_sub.add_parser("native", help="Normalize a native hook payload and return a native response.")
    bridge_native.add_argument("--agent", choices=("claude-code", "codex", "opencode", "generic"), required=True)
    bridge_native.add_argument("--event", required=True)
    bridge_conformance = bridge_sub.add_parser("conformance", help="Run native bridge response-shape conformance checks.")

    mcp = subparsers.add_parser("mcp", help="MCP broker and inspection commands.")
    mcp.set_defaults(handler=handle_mcp)
    mcp_sub = mcp.add_subparsers(dest="mcp_command", required=True)
    mcp_broker = mcp_sub.add_parser("broker-step", help="Run one transparent MCP broker step for a JSON message.")
    mcp_broker.add_argument("--message", required=True)
    mcp_stdio = mcp_sub.add_parser("broker-stdio", help="Run a transparent JSONL stdio broker with transcript capture.")
    mcp_stdio.add_argument("--input", required=True)
    mcp_stdio.add_argument("--output", required=True)
    mcp_stdio.add_argument("--transcript", required=True)

    coverage = subparsers.add_parser("coverage", help="Export coverage-aware proof reports.")
    coverage.set_defaults(handler=handle_coverage)
    coverage_sub = coverage.add_subparsers(dest="coverage_command", required=True)
    coverage_html = coverage_sub.add_parser("html", help="Export a coverage matrix HTML report from proof JSON.")
    coverage_html.add_argument("--proof", required=True)
    coverage_html.add_argument("--out", required=True)

    graph = subparsers.add_parser("graph", help="Export and query ledger-derived execution path graphs.")
    graph.set_defaults(handler=handle_graph)
    graph_sub = graph.add_subparsers(dest="graph_command", required=True)
    graph_export = graph_sub.add_parser("export", help="Export execution graph JSON.")
    graph_export.add_argument("--ledger", required=True)
    graph_export.add_argument("--out", required=True)
    graph_html = graph_sub.add_parser("html", help="Export execution graph HTML.")
    graph_html.add_argument("--ledger", required=True)
    graph_html.add_argument("--out", required=True)
    graph_query = graph_sub.add_parser("query", help="Query graph upstream or downstream from a node.")
    graph_query.add_argument("--ledger", required=True)
    graph_query.add_argument("--target", required=True)
    graph_query.add_argument("--direction", choices=("upstream", "downstream"), default="upstream")

    mediation = subparsers.add_parser("mediation", help="Inspect and resolve unified mediation records.")
    mediation.set_defaults(handler=handle_mediation)
    mediation_sub = mediation.add_subparsers(dest="mediation_command", required=True)
    mediation_inspect = mediation_sub.add_parser("inspect", help="Replay mediation events from a ledger.")
    mediation_inspect.add_argument("--ledger", required=True)
    mediation_resolve = mediation_sub.add_parser("resolve", help="Resolve a paused mediation item.")
    mediation_resolve.add_argument("--ledger", required=True)
    mediation_resolve.add_argument("--mediation", required=True)
    mediation_resolve.add_argument("--actor", required=True)
    mediation_resolve.add_argument("--status", choices=("approved", "rejected"), required=True)
    mediation_resolve.add_argument("--reason", required=True)
    mediation_replay = mediation_sub.add_parser("replay", help="Replay mediation records from a ledger.")
    mediation_replay.add_argument("--ledger", required=True)

    supervise = subparsers.add_parser("supervise", help="Run process-group supervision checks.")
    supervise.set_defaults(handler=handle_supervise)
    supervise_sub = supervise.add_subparsers(dest="supervise_command", required=True)
    supervise_run = supervise_sub.add_parser("run", help="Run a command under process-group supervision.")
    supervise_run.add_argument("--target", default=None)
    supervise_run.add_argument("cmd", nargs=argparse.REMAINDER)

    runtime = subparsers.add_parser("runtime", help="Runtime audit helpers.")
    runtime.set_defaults(handler=handle_runtime)
    runtime_sub = runtime.add_subparsers(dest="runtime_command", required=True)
    analyze = runtime_sub.add_parser("analyze-event", help="Analyze a runtime event JSON payload.")
    analyze.add_argument("--event", required=True, help="JSON event payload.")
    analyze.add_argument("--session", default=None)
    analyze.add_argument("--ledger", default=None)
    analyze.add_argument("--review", choices=("off", "auto", "always", "required"), default="auto")
    analyze.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    analyze.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    analyze.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(analyze)
    record = runtime_sub.add_parser("record-event", help="Append a runtime event to a v0.1 ledger.")
    record.add_argument("--event", required=True, help="JSON event payload.")
    record.add_argument("--session", default=None)
    record.add_argument("--ledger", "--log", default=".kappaski/session.jsonl", help="JSONL ledger path.")
    record.add_argument("--review", choices=("off", "auto", "always", "required"), default="auto")
    record.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    record.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    record.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(record)
    shell = runtime_sub.add_parser("shell", help="Run a shell command with audit logging and policy decisions.")
    shell.add_argument("--session", default=None)
    shell.add_argument("--ledger", "--log", default=".kappaski/session.jsonl", help="JSONL ledger path.")
    shell.add_argument("--agent", default=None)
    shell.add_argument("--target", default=None)
    shell.add_argument("--review", choices=("off", "auto", "always", "required"), default="auto")
    shell.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    shell.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    shell.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(shell)
    shell.add_argument("cmd", nargs=argparse.REMAINDER, help="Command to run after --.")
    approve = runtime_sub.add_parser("approve", help="Record approval evidence for a policy decision.")
    approve.add_argument("--ledger", required=True)
    approve.add_argument("--decision", required=True)
    approve.add_argument("--approver", default=None)
    approve.add_argument("--reason", default=None)
    reject = runtime_sub.add_parser("reject", help="Record rejection evidence for a policy decision.")
    reject.add_argument("--ledger", required=True)
    reject.add_argument("--decision", required=True)
    reject.add_argument("--approver", default=None)
    reject.add_argument("--reason", default=None)
    outcome = runtime_sub.add_parser("outcome", help="Record the observed execution outcome for a decision or invocation.")
    outcome.add_argument("--ledger", required=True)
    outcome.add_argument("--decision", default=None)
    outcome.add_argument("--invocation", default=None)
    outcome.add_argument("--status", choices=("executed", "blocked", "skipped", "overridden", "failed"), required=True)
    outcome.add_argument("--actor", default=None)
    outcome.add_argument("--reason", default=None)

    approval = subparsers.add_parser("approval", help="List and resolve approval inbox items.")
    approval.set_defaults(handler=handle_approval)
    approval_sub = approval.add_subparsers(dest="approval_command", required=True)
    approval_list = approval_sub.add_parser("list", help="List approval items from a ledger.")
    approval_list.add_argument("--ledger", required=True)
    approval_list.add_argument("--status", default=None)
    approval_approve = approval_sub.add_parser("approve", help="Approve one decision or all missing approvals.")
    approval_approve.add_argument("--ledger", required=True)
    approval_approve.add_argument("--decision", default=None)
    approval_approve.add_argument("--all", action="store_true")
    approval_approve.add_argument("--approver", default=None)
    approval_approve.add_argument("--reason", default=None)
    approval_reject = approval_sub.add_parser("reject", help="Reject one decision or all missing approvals.")
    approval_reject.add_argument("--ledger", required=True)
    approval_reject.add_argument("--decision", default=None)
    approval_reject.add_argument("--all", action="store_true")
    approval_reject.add_argument("--approver", default=None)
    approval_reject.add_argument("--reason", default=None)

    replay = subparsers.add_parser("replay", help="Export runtime replay reports.")
    replay.set_defaults(handler=handle_replay)
    replay_sub = replay.add_subparsers(dest="replay_command", required=True)
    replay_export = replay_sub.add_parser("export", help="Export a static HTML replay report.")
    replay_export.add_argument("--ledger", required=True)
    replay_export.add_argument("--out", required=True)
    replay_export.add_argument("--gate-mode", choices=("audit", "managed", "ci"), default="managed")
    replay_export.add_argument("--case", default=None)
    replay_export.add_argument("--no-raw", action="store_true")
    add_profile_args(replay_export)

    policy = subparsers.add_parser("policy", help="Inspect policy decisions and merged evaluations.")
    policy.set_defaults(handler=handle_policy)
    policy_sub = policy.add_subparsers(dest="policy_command", required=True)
    policy_validate = policy_sub.add_parser("validate", help="Validate a Kappaski-native policy-as-code profile.")
    policy_validate.add_argument("--profile", required=True)
    policy_test = policy_sub.add_parser("test", help="Run built-in product tests against a policy-as-code profile.")
    policy_test.add_argument("--profile", required=True)
    policy_explain = policy_sub.add_parser("explain", help="Explain a policy decision from the ledger.")
    policy_explain.add_argument("--ledger", required=True)
    policy_explain.add_argument("--decision", default=None)
    policy_explain.add_argument("--invocation", default=None)
    policy_check_path = policy_sub.add_parser("check-path", help="Evaluate path-aware policy over a ledger.")
    policy_check_path.add_argument("--ledger", required=True)
    policy_check_path.add_argument("--profile", default=None)
    policy_check_path.add_argument("--out", default=None)

    review = subparsers.add_parser("review", help="Inspect semantic review records.")
    review.set_defaults(handler=handle_review)
    review_sub = review.add_subparsers(dest="review_command", required=True)
    review_invocation = review_sub.add_parser("invocation", help="Show semantic review output for an invocation.")
    review_invocation.add_argument("--ledger", required=True)
    review_invocation.add_argument("--invocation", required=True)
    review_invocation.add_argument("--review", default=None)

    eval_parser = subparsers.add_parser("eval", help="Run Kappaski effectiveness benchmarks.")
    eval_parser.set_defaults(handler=handle_eval)
    eval_sub = eval_parser.add_subparsers(dest="eval_command", required=True)
    eval_list = eval_sub.add_parser("list", help="List built-in benchmark suites.")
    eval_report = eval_sub.add_parser("report", help="Run a benchmark suite and write a JSON report.")
    eval_report.add_argument("--suite", default="full-product-readiness")
    eval_report.add_argument("--out", required=True)
    benchmark = eval_sub.add_parser("benchmark", help="Run a built-in benchmark suite through the runtime pipeline.")
    benchmark.add_argument("--suite", default="v0.2-semantic")
    benchmark.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    benchmark.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")

    experiment = subparsers.add_parser("experiment", help="Run benchmark-derived LLM agent experiment suites.")
    experiment.set_defaults(handler=handle_experiment)
    experiment_sub = experiment.add_subparsers(dest="experiment_command", required=True)
    experiment_list = experiment_sub.add_parser("list", help="List benchmark experiment suites.")
    experiment_run = experiment_sub.add_parser("run", help="Run an experiment suite and write artifacts.")
    experiment_run.add_argument("--suite", default="control-plane-core")
    experiment_run.add_argument("--out-dir", required=True)
    experiment_report = experiment_sub.add_parser("report", help="Render an experiment run JSON as HTML.")
    experiment_report.add_argument("--run", required=True)
    experiment_report.add_argument("--out", required=True)
    experiment_validate = experiment_sub.add_parser("validate-fixtures", help="Validate benchmark-derived experiment fixture JSON files.")
    experiment_validate.add_argument("--root", default="benchmarks/experiments")
    experiment_paper = experiment_sub.add_parser("paper-suite", help="Generate the v0.39 paper-ready experiment bundle.")
    experiment_paper.add_argument("--out-dir", required=True)

    gate = subparsers.add_parser("gate", help="Consume proof and ledger artifacts as release/CI gates.")
    gate.set_defaults(handler=handle_gate)
    gate_sub = gate.add_subparsers(dest="gate_command", required=True)
    gate_verify = gate_sub.add_parser("verify", help="Evaluate proof/ledger artifacts against a gate mode.")
    gate_verify.add_argument("--proof", default=None)
    gate_verify.add_argument("--ledger", default=None)
    gate_verify.add_argument("--mode", choices=("audit", "managed", "ci"), default="managed")
    gate_verify.add_argument("--out", default=None)
    add_profile_args(gate_verify)

    proof = subparsers.add_parser("proof", help="Export or verify proof reports.")
    proof.set_defaults(handler=handle_proof)
    proof_sub = proof.add_subparsers(dest="proof_command", required=True)
    proof_export = proof_sub.add_parser("export", help="Export a proof JSON report.")
    proof_export.add_argument("--ledger", "--events", default=".kappaski/session.jsonl")
    proof_export.add_argument("--out", "--output", default=None)
    proof_verify = proof_sub.add_parser("verify", help="Verify a proof, a ledger, or both.")
    proof_verify.add_argument("--proof", default=None)
    proof_verify.add_argument("--ledger", "--events", default=None)

    evidence = subparsers.add_parser("evidence", help="Export and verify enterprise evidence bundles.")
    evidence.set_defaults(handler=handle_evidence)
    evidence_sub = evidence.add_subparsers(dest="evidence_command", required=True)
    evidence_export = evidence_sub.add_parser("export", help="Export a v0.27 evidence bundle from a ledger.")
    evidence_export.add_argument("--ledger", required=True)
    evidence_export.add_argument("--out-dir", required=True)
    evidence_export.add_argument("--profile", default=None)
    evidence_verify = evidence_sub.add_parser("verify", help="Verify an evidence bundle manifest.")
    evidence_verify.add_argument("--bundle", required=True)

    audit = subparsers.add_parser("audit", help="Generate audit reports from runtime evidence.")
    audit.set_defaults(handler=handle_audit)
    audit_sub = audit.add_subparsers(dest="audit_command", required=True)
    audit_report = audit_sub.add_parser("report", help="Export audit JSON/HTML through an evidence bundle.")
    audit_report.add_argument("--ledger", required=True)
    audit_report.add_argument("--out-dir", required=True)


    roadmap = subparsers.add_parser("roadmap", help="Inspect implementation coverage against the roadmap.")
    roadmap.set_defaults(handler=handle_roadmap)
    roadmap_sub = roadmap.add_subparsers(dest="roadmap_command", required=True)
    roadmap_status = roadmap_sub.add_parser("status", help="Show roadmap implementation coverage and gaps.")
    roadmap_status.add_argument("--require-full", action="store_true")
    roadmap_status.add_argument("--require-external-validation", action="store_true", help="Fail if optional external/live benchmark validation has not been run.")

    demo = subparsers.add_parser("demo", help="Generate packaged product demos and audit artifacts.")
    demo.set_defaults(handler=handle_demo)
    demo_sub = demo.add_subparsers(dest="demo_command", required=True)
    demo_enterprise = demo_sub.add_parser("enterprise-audit", help="Generate the v0.14 enterprise security audit demo.")
    demo_enterprise.add_argument("--out-dir", required=True)
    demo_enterprise.add_argument("--mode", choices=("scripted", "live-adapter"), default="scripted")
    demo_pre_v1 = demo_sub.add_parser("pre-v1-control-plane", help="Generate the v0.24 pre-v1 control-plane demo package.")
    demo_pre_v1.add_argument("--out-dir", required=True)
    demo_real_world = demo_sub.add_parser("real-world-risk-cases", help="Generate public-source risk mapping plus before/during/after Kappaski demo artifacts.")
    demo_real_world.add_argument("--out-dir", required=True)
    demo_signoff = demo_sub.add_parser("signoff", help="Record ledger-backed enterprise audit signoff.")
    demo_signoff.add_argument("--ledger", required=True)
    demo_signoff.add_argument("--actor", required=True)
    demo_signoff.add_argument("--status", choices=("approved", "rejected", "needs_followup"), required=True)
    demo_signoff.add_argument("--reason", required=True)
    demo_signoff.add_argument("--report", default=None)

    post = subparsers.add_parser("post-runtime", help="Summarize a JSONL runtime audit log.")
    post.set_defaults(handler=handle_post_runtime)
    post.add_argument("--events", default=".kappaski/session.jsonl", help="JSONL event log path.")

    for rc_name in ("release-candidate", "rc"):
        rc_parser = subparsers.add_parser(rc_name, help="Run the v0.40 release-candidate readiness gate.")
        rc_parser.set_defaults(handler=handle_release_candidate)
        rc_sub = rc_parser.add_subparsers(dest="rc_command", required=True)
        rc_verify = rc_sub.add_parser("verify", help="Verify pytest, roadmap, benchmarks, docs, and artifacts.")
        rc_verify.add_argument("--out-dir", required=True)
        rc_verify.add_argument("--skip-pytest", action="store_true")

    return parser
