from __future__ import annotations

import argparse

from .common import add_profile_args
from .governance import handle_corpus, handle_daemon, handle_identity, handle_profile, handle_teamrun


def register_governance_commands(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    corpus = subparsers.add_parser("corpus", help="Inspect pinned real-world Skill/tool corpora.")
    corpus.set_defaults(handler=handle_corpus)
    corpus_sub = corpus.add_subparsers(dest="corpus_command", required=True)
    corpus_scan = corpus_sub.add_parser("scan", help="Scan pinned real corpus snapshots for capability and risk surface.")
    corpus_scan.add_argument("--root", default="benchmarks/corpora")

    identity = subparsers.add_parser("identity", help="Declare principals, bind agent identity, and inspect accountability facts.")
    identity.set_defaults(handler=handle_identity)
    identity_sub = identity.add_subparsers(dest="identity_command", required=True)
    identity_declare = identity_sub.add_parser("declare", help="Declare a local principal.")
    identity_declare.add_argument("--principal", required=True)
    identity_declare.add_argument("--display-name", default=None)
    identity_declare.add_argument("--source", default="local")
    identity_declare.add_argument("--out", default=None)
    identity_bind = identity_sub.add_parser("bind", help="Append principal, agent, credential, and grant facts to a ledger.")
    identity_bind.add_argument("--ledger", required=True)
    identity_bind.add_argument("--session", required=True)
    identity_bind.add_argument("--principal", required=True)
    identity_bind.add_argument("--agent", required=True)
    identity_bind.add_argument("--adapter-agent", default=None)
    identity_bind.add_argument("--scope", action="append", default=[])
    identity_bind.add_argument("--resource", action="append", default=[])
    identity_bind.add_argument("--env-key", action="append", default=[])
    identity_inspect = identity_sub.add_parser("inspect", help="Inspect accountability facts from a ledger.")
    identity_inspect.add_argument("--ledger", required=True)

    daemon = subparsers.add_parser("daemon", help="Runtime authority and session registry commands.")
    daemon.set_defaults(handler=handle_daemon)
    daemon_sub = daemon.add_subparsers(dest="daemon_command", required=True)
    daemon_init = daemon_sub.add_parser("init", help="Initialize the local runtime authority registry.")
    daemon_init.add_argument("--target", default=".")
    daemon_status = daemon_sub.add_parser("status", help="Show local runtime authority status.")
    daemon_status.add_argument("--target", default=".")
    daemon_record = daemon_sub.add_parser("record-event", help="Record a runtime event through the authority.")
    daemon_record.add_argument("--target", default=".")
    daemon_record.add_argument("--session", required=True)
    daemon_record.add_argument("--event", required=True)
    daemon_record.add_argument("--review", choices=("off", "auto", "always", "required"), default="auto")
    daemon_record.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    daemon_record.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    daemon_record.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(daemon_record)
    daemon_heartbeat = daemon_sub.add_parser("heartbeat", help="Update session heartbeat metadata.")
    daemon_heartbeat.add_argument("--target", default=".")
    daemon_heartbeat.add_argument("--session", required=True)
    daemon_heartbeat.add_argument("--actor", default=None)
    daemon_register = daemon_sub.add_parser("register-capabilities", help="Register scanned adapter/skill capabilities into a session ledger.")
    daemon_register.add_argument("--target", default=".")
    daemon_register.add_argument("--session", required=True)
    daemon_register.add_argument("--corpus-root", default="benchmarks/corpora")
    daemon_register.add_argument("--adapter", default="unknown")
    daemon_register.add_argument("--review", choices=("off", "auto", "always", "required"), default="off")
    daemon_register.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="managed")
    daemon_register.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")
    daemon_register.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    add_profile_args(daemon_register)
    daemon_approve = daemon_sub.add_parser("approve", help="Resolve a pending approval through the authority.")
    daemon_approve.add_argument("--target", default=".")
    daemon_approve.add_argument("--session", required=True)
    daemon_approve.add_argument("--decision", required=True)
    daemon_approve.add_argument("--approver", default=None)
    daemon_approve.add_argument("--reason", default=None)
    daemon_reject = daemon_sub.add_parser("reject", help="Reject a pending approval through the authority.")
    daemon_reject.add_argument("--target", default=".")
    daemon_reject.add_argument("--session", required=True)
    daemon_reject.add_argument("--decision", required=True)
    daemon_reject.add_argument("--approver", default=None)
    daemon_reject.add_argument("--reason", default=None)
    daemon_outcome = daemon_sub.add_parser("outcome", help="Record execution outcome through the authority.")
    daemon_outcome.add_argument("--target", default=".")
    daemon_outcome.add_argument("--session", required=True)
    daemon_outcome.add_argument("--decision", default=None)
    daemon_outcome.add_argument("--invocation", default=None)
    daemon_outcome.add_argument("--status", choices=("executed", "blocked", "skipped", "overridden", "failed"), required=True)
    daemon_outcome.add_argument("--actor", default=None)
    daemon_outcome.add_argument("--reason", default=None)
    daemon_session = daemon_sub.add_parser("session", help="Manage authority sessions.")
    daemon_session_sub = daemon_session.add_subparsers(dest="daemon_session_command", required=True)
    daemon_session_create = daemon_session_sub.add_parser("create", help="Create and register a managed session.")
    daemon_session_create.add_argument("--target", default=".")
    daemon_session_create.add_argument("--agent", default=None)
    daemon_session_create.add_argument("--goal", default=None)
    daemon_session_create.add_argument("--session-id", default=None)
    daemon_session_create.add_argument("--ledger", default=None)
    daemon_session_create.add_argument("--preflight", default=None)
    daemon_session_create.add_argument("--no-preflight", action="store_true")
    add_profile_args(daemon_session_create)
    daemon_session_list = daemon_session_sub.add_parser("list", help="List registered sessions.")
    daemon_session_list.add_argument("--target", default=".")
    daemon_session_list.add_argument("--include-deleted", action="store_true")
    daemon_session_show = daemon_session_sub.add_parser("show", help="Show a registered session.")
    daemon_session_show.add_argument("--target", default=".")
    daemon_session_show.add_argument("--session", required=True)
    for _name in ("pause", "resume", "interrupt", "stop", "delete"):
        _parser = daemon_session_sub.add_parser(_name, help=f"{_name.capitalize()} a registered session.")
        _parser.add_argument("--target", default=".")
        _parser.add_argument("--session", required=True)
        _parser.add_argument("--reason", default=None)

    profile = subparsers.add_parser("profile", help="Resolve TOML/JSON policy profiles with session > repo > team precedence.")
    profile.set_defaults(handler=handle_profile)
    profile_sub = profile.add_subparsers(dest="profile_command", required=True)
    profile_resolve = profile_sub.add_parser("resolve", help="Resolve policy profile precedence.")
    profile_resolve.add_argument("--team", default=None)
    profile_resolve.add_argument("--repo", default=None)
    profile_resolve.add_argument("--session", default=None)
    profile_break_glass = profile_sub.add_parser("break-glass", help="Record a ledger-backed break-glass override.")
    profile_break_glass.add_argument("--ledger", required=True)
    profile_break_glass.add_argument("--session", required=True)
    profile_break_glass.add_argument("--actor", required=True)
    profile_break_glass.add_argument("--reason", required=True)
    profile_break_glass.add_argument("--scope", required=True)
    profile_break_glass.add_argument("--expires-at", default=None)
    profile_distribute = profile_sub.add_parser("distribute", help="Create a signed profile distribution bundle.")
    profile_distribute.add_argument("--profile", required=True)
    profile_distribute.add_argument("--scope", choices=("team", "repo", "session"), required=True)
    profile_distribute.add_argument("--distributed-by", required=True)
    profile_review = profile_sub.add_parser("review-override", help="Record administrator/auditor review of a break-glass override.")
    profile_review.add_argument("--ledger", required=True)
    profile_review.add_argument("--override", required=True)
    profile_review.add_argument("--reviewer", required=True)
    profile_review.add_argument("--status", choices=("approved", "rejected"), required=True)
    profile_review.add_argument("--reason", required=True)
    profile_registry = profile_sub.add_parser("registry", help="Create an enterprise profile registry from inline profile JSON.")
    profile_registry.add_argument("--owner", required=True)
    profile_registry.add_argument("--profile", action="append", required=True)
    profile_pin = profile_sub.add_parser("pin", help="Pin a profile from a registry JSON file.")
    profile_pin.add_argument("--registry", required=True)
    profile_pin.add_argument("--scope", choices=("team", "repo", "session"), required=True)
    profile_pin.add_argument("--name", required=True)
    profile_pin.add_argument("--distributed-by", required=True)
    profile_pin.add_argument("--out", default=None)
    profile_verify = profile_sub.add_parser("verify", help="Verify a pinned profile bundle against a registry.")
    profile_verify.add_argument("--registry", required=True)
    profile_verify.add_argument("--bundle", required=True)

    teamrun = subparsers.add_parser("teamrun", help="Create and inspect multi-user TeamRun and Handoff records.")
    teamrun.set_defaults(handler=handle_teamrun)
    teamrun_sub = teamrun.add_subparsers(dest="teamrun_command", required=True)
    teamrun_create = teamrun_sub.add_parser("create", help="Create a TeamRun record.")
    teamrun_create.add_argument("--ledger", default=None)
    teamrun_create.add_argument("--name", required=True)
    teamrun_create.add_argument("--user", action="append", default=[])
    teamrun_identity = teamrun_sub.add_parser("identity", help="Declare and validate agent identity.")
    teamrun_identity.add_argument("--ledger", default=None)
    teamrun_identity.add_argument("--agent", required=True)
    teamrun_identity.add_argument("--declared-by", required=True)
    teamrun_identity.add_argument("--adapter-agent", default=None)
    teamrun_handoff = teamrun_sub.add_parser("handoff", help="Create a Handoff record.")
    teamrun_handoff.add_argument("--ledger", default=None)
    teamrun_handoff.add_argument("--source-agent", required=True)
    teamrun_handoff.add_argument("--target-agent", required=True)
    teamrun_handoff.add_argument("--resource", action="append", default=[])
    teamrun_handoff.add_argument("--taint-mode", choices=("resource-reference", "session-wide"), default="resource-reference")
    teamrun_handoff.add_argument("--session-tainted", action="store_true")
    teamrun_blackboard = teamrun_sub.add_parser("blackboard", help="Record a TeamRun blackboard entry.")
    teamrun_blackboard.add_argument("--ledger", required=True)
    teamrun_blackboard.add_argument("--teamrun", required=True)
    teamrun_blackboard.add_argument("--author", required=True)
    teamrun_blackboard.add_argument("--content", required=True)
    teamrun_blackboard.add_argument("--resource", action="append", default=[])
    teamrun_delegate = teamrun_sub.add_parser("delegate-grant", help="Record a restrict-only grant delegation.")
    teamrun_delegate.add_argument("--ledger", required=True)
    teamrun_delegate.add_argument("--source-agent", required=True)
    teamrun_delegate.add_argument("--target-agent", required=True)
    teamrun_delegate.add_argument("--parent-scope", required=True)
    teamrun_delegate.add_argument("--delegate-scope", required=True)
    teamrun_proof = teamrun_sub.add_parser("proof", help="Export TeamRun proof facts from a ledger.")
    teamrun_proof.add_argument("--ledger", required=True)
    teamrun_proof.add_argument("--out", default=None)
    teamrun_aggregate = teamrun_sub.add_parser("aggregate", help="Aggregate TeamRun proof facts across multiple ledgers.")
    teamrun_aggregate.add_argument("--ledger", action="append", required=True)
    teamrun_aggregate.add_argument("--out", default=None)
    teamrun_timeline = teamrun_sub.add_parser("timeline", help="Export a multi-ledger TeamRun timeline HTML report.")
    teamrun_timeline.add_argument("--ledger", action="append", required=True)
    teamrun_timeline.add_argument("--out", required=True)

