from __future__ import annotations

import argparse

from invart.evaluation.harness import SWE_BENCH_FULL_DATASET, SWE_BENCH_FULL_EXPECTED_INSTANCES, SWE_BENCH_LITE_DATASET
from invart.surfaces.adapter_profiles import adapter_profile_ids
from .common import add_profile_args
from .integrations import handle_adapter, handle_bridge, handle_coverage, handle_enforce, handle_external_validation, handle_graph, handle_harness, handle_launcher, handle_mcp, handle_mediation, handle_native, handle_real_agent, handle_supervise


def register_integration_commands(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    adapter = subparsers.add_parser("adapter", help="Reference adapter wrapper workflows.")
    adapter.set_defaults(handler=handle_adapter)
    adapter_sub = adapter.add_subparsers(dest="adapter_command", required=True)
    adapter_run = adapter_sub.add_parser("run", help="Run a child command through a Invart reference adapter wrapper.")
    adapter_run.add_argument("--target", default=".")
    adapter_run.add_argument("--agent", default=None)
    adapter_run.add_argument("--goal", default=None)
    adapter_run.add_argument("--session-id", default=None)
    adapter_run.add_argument("--out-dir", default=None)
    adapter_run.add_argument("--corpus-root", default="benchmarks/corpora")
    adapter_run.add_argument("--capabilities", choices=("off", "audit", "managed"), default="audit")
    adapter_run.add_argument("--gate", choices=("off", "audit", "managed", "ci"), default="off")
    adapter_run.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    adapter_run.add_argument("--enforcement", choices=("off", "file-write"), default="off")
    adapter_run.add_argument("--no-preflight", action="store_true")
    adapter_run.add_argument("cmd", nargs=argparse.REMAINDER)
    adapter_inspect = adapter_sub.add_parser("inspect", help="Inspect and verify an adapter runtime package manifest.")
    adapter_inspect.add_argument("--package", required=True)
    adapter_package = adapter_sub.add_parser("package", help="Package an existing adapter ledger into an evidence bundle.")
    adapter_package.add_argument("--ledger", required=True)
    adapter_package.add_argument("--out-dir", required=True)
    adapter_profile = adapter_sub.add_parser("profile", help="Inspect a hardened adapter profile.")
    adapter_profile.add_argument("--kind", choices=adapter_profile_ids(), default="claude-code")
    adapter_claude_check = adapter_sub.add_parser("claude-code-check", help="Check a real Claude Code binary environment when available.")
    adapter_claude_check.add_argument("--binary", default="claude")
    adapter_claude = adapter_sub.add_parser("claude-code", help="Run a command through the Claude Code wrapper/hook bridge.")
    adapter_claude.add_argument("--target", default=".")
    adapter_claude.add_argument("--out-dir", default=None)
    adapter_claude.add_argument("--hook-events", default=None)
    adapter_claude.add_argument("--session-id", default=None)
    adapter_claude.add_argument("--no-preflight", action="store_true")
    adapter_claude.add_argument("--policy-mode", choices=("audit", "advisory", "managed", "ci"), default="advisory")
    adapter_claude.add_argument("--enforcement", choices=("off", "file-write"), default="off")
    adapter_claude.add_argument("cmd", nargs=argparse.REMAINDER)

    harness = subparsers.add_parser("harness", help="Compare real agent harness compatibility artifacts.")
    harness.set_defaults(handler=handle_harness)
    harness_sub = harness.add_subparsers(dest="harness_command", required=True)
    harness_compare = harness_sub.add_parser("compare", help="Compare baseline and Invart-wrapped harness artifacts.")
    harness_compare.add_argument("--baseline", required=True)
    harness_compare.add_argument("--wrapped", required=True)
    harness_compare.add_argument("--case", default=None)
    harness_swe = harness_sub.add_parser("swe-bench-lite", help="Run or compare optional SWE-Bench Lite harness artifacts.")
    harness_swe.add_argument("--case", required=True)
    harness_swe.add_argument("--baseline-artifact", default=None)
    harness_swe.add_argument("--wrapped-artifact", default=None)
    harness_swe.add_argument("--out", default=None)
    harness_swe.add_argument("--dependency", default="docker")
    harness_swe.add_argument("--skip-if-unavailable", action="store_true")
    harness_swe.add_argument("--baseline-command", default=None, help="Command that produces the baseline artifact as its last argument.")
    harness_swe.add_argument("--wrapped-command", default=None, help="Command that produces the Invart-wrapped artifact as its last argument.")
    harness_official = harness_sub.add_parser("swe-bench-official", help="Run the official SWE-Bench Lite harness entrypoint when installed.")
    harness_official.add_argument("--python", default="python")
    harness_official.add_argument("--dataset-name", default=SWE_BENCH_LITE_DATASET)
    harness_official.add_argument("--split", default="test")
    harness_official.add_argument("--instance-id", action="append", default=[])
    harness_official.add_argument("--predictions-path", default="gold")
    harness_official.add_argument("--run-id", default="invart_smoke")
    harness_official.add_argument("--report-dir", default=None)
    harness_official.add_argument("--timeout", type=int, default=60)
    harness_official.add_argument("--max-workers", type=int, default=1)
    harness_official.add_argument("--cache-level", default="instance")
    harness_official.add_argument("--clean", action="store_true")
    harness_official.add_argument("--work-dir", default=None)
    harness_official.add_argument("--out", default=None)
    harness_official.add_argument("--command", dest="override_command", default=None, help="Override command for test or custom harness use.")
    harness_official.add_argument("--report-path", default=None, help="Explicit official report JSON path for command override.")
    harness_managed = harness_sub.add_parser("managed-check", help="Run a command through managed harness pause/approval/resume compatibility flow.")
    harness_managed.add_argument("--target", default=".")
    harness_managed.add_argument("--case", default=None)
    harness_managed.add_argument("--approval-actor", default="human-approver")
    harness_managed.add_argument("cmd", nargs=argparse.REMAINDER)

    external_validation = subparsers.add_parser("external-validation", help="Run explicit optional upstream/live benchmark validation.")
    external_validation.set_defaults(handler=handle_external_validation)
    external_validation_sub = external_validation.add_subparsers(dest="external_validation_command", required=True)
    swe_full = external_validation_sub.add_parser("swe-bench-full", help="Run and validate the official full SWE-Bench evaluation chain.")
    swe_full.add_argument("--python", default="python")
    swe_full.add_argument("--dataset-name", default=SWE_BENCH_FULL_DATASET)
    swe_full.add_argument("--split", default="test")
    swe_full.add_argument("--predictions-path", default="gold")
    swe_full.add_argument("--run-id", default="invart_swe_bench_full")
    swe_full.add_argument("--report-dir", default=None)
    swe_full.add_argument("--timeout", type=int, default=1800)
    swe_full.add_argument("--max-workers", type=int, default=1)
    swe_full.add_argument("--cache-level", default="instance")
    swe_full.add_argument("--clean", action="store_true")
    swe_full.add_argument("--work-dir", default=None)
    swe_full.add_argument("--out", default=None)
    swe_full.add_argument("--command", dest="override_command", default=None, help="Override command for contract tests or custom official harness use.")
    swe_full.add_argument("--report-path", default=None, help="Explicit official report JSON path.")
    swe_full.add_argument("--instance-results-path", default=None, help="Explicit official instance_results.jsonl path.")
    swe_full.add_argument("--expected-total-instances", type=int, default=SWE_BENCH_FULL_EXPECTED_INSTANCES)
    swe_full.add_argument("--allow-subset", action="store_true", help="Mark this as a subset smoke run; it will not satisfy full external validation.")

    real_agent = subparsers.add_parser("real-agent", help="Validate real or fixture-backed agent products through Invart profiles.")
    real_agent.set_defaults(handler=handle_real_agent)
    real_agent_sub = real_agent.add_subparsers(dest="real_agent_command", required=True)
    real_agent_check = real_agent_sub.add_parser("check", help="Run agent profile and binary-shaped conformance checks.")
    real_agent_check.add_argument("--agent", action="append", choices=adapter_profile_ids(), default=[])
    real_agent_check.add_argument("--binary", action="append", default=[], help="Override an agent binary as agent-id=/path/to/binary.")
    real_agent_check.add_argument("--require-live", action="store_true", help="Fail when requested real agent binaries are missing.")
    real_agent_check.add_argument("--out-dir", default=".invart/real-agent-conformance")
    real_agent_report = real_agent_sub.add_parser("report", help="Render a real-agent conformance HTML report from a run directory.")
    real_agent_report.add_argument("--run-dir", required=True)
    real_agent_report.add_argument("--out", required=True)

    enforce = subparsers.add_parser("enforce", help="Evaluate enforcement guard decisions.")
    enforce.set_defaults(handler=handle_enforce)
    enforce_sub = enforce.add_subparsers(dest="enforce_command", required=True)
    enforce_check = enforce_sub.add_parser("check", help="Check an event against an enforcement domain.")
    enforce_check.add_argument("--event", required=True)
    enforce_check.add_argument("--domain", choices=("file-write", "env-secrets", "network-egress"), default="file-write")
    add_profile_args(enforce_check)
    enforce_shim_spec = enforce_sub.add_parser("shim-spec", help="Show Rust shim contract and source availability.")
    enforce_shim_spec.add_argument("--domain", choices=("file-write",), default="file-write")
    enforce_build = enforce_sub.add_parser("rust-build-check", help="Run cargo check for the Rust shim when cargo is available.")
    enforce_build.add_argument("--skip-if-unavailable", action="store_true")
    enforce_shim_decision = enforce_sub.add_parser("shim-decision", help="Evaluate an event with the compiled Rust shim.")
    enforce_shim_decision.add_argument("--event", required=True)
    enforce_shim_decision.add_argument("--crate", default=None)
    enforce_run = enforce_sub.add_parser("run-file-write", help="Run a command through the Rust file-write shim before execution.")
    enforce_run.add_argument("--ledger", default=None)
    enforce_run.add_argument("--session", default=None)
    enforce_run.add_argument("--target", default=None)
    enforce_run.add_argument("--allow-approval-required", action="store_true", help="Execute require_approval commands in open/audit-style mode.")
    enforce_run.add_argument("--crate", default=None)
    enforce_run.add_argument("cmd", nargs=argparse.REMAINDER)
    enforce_run_domain = enforce_sub.add_parser("run", help="Run a command through a selected enforcement domain before execution.")
    enforce_run_domain.add_argument("--domain", choices=("file-write", "env-secrets", "network-egress"), required=True)
    enforce_run_domain.add_argument("--event", default=None)
    enforce_run_domain.add_argument("--ledger", default=None)
    enforce_run_domain.add_argument("--session", default=None)
    enforce_run_domain.add_argument("--target", default=None)
    enforce_run_domain.add_argument("--allow-approval-required", action="store_true")
    enforce_run_domain.add_argument("cmd", nargs=argparse.REMAINDER)

    native = subparsers.add_parser("native", help="Inspect and manage native agent integration surfaces.")
    native.set_defaults(handler=handle_native)
    native_sub = native.add_subparsers(dest="native_command", required=True)
    native_inventory = native_sub.add_parser("inventory", help="Inventory hooks, plugins, extensions, rules, MCP, sandbox, and config surfaces.")
    native_inventory.add_argument("--target", default=".")
    native_inventory.add_argument("--include-global-config", action="store_true")
    native_matrix = native_sub.add_parser("matrix", help="Export a vendor safety capability and coverage matrix.")
    native_matrix.add_argument("--target", default=".")
    native_matrix.add_argument("--include-global-config", action="store_true")
    native_unmanaged = native_sub.add_parser("unmanaged", help="Detect unregistered or unmanaged agent surfaces.")
    native_unmanaged.add_argument("--target", default=".")
    native_unmanaged.add_argument("--include-global-config", action="store_true")
    native_inspect = native_sub.add_parser("inspect", help="Alias for the native capability matrix.")
    native_inspect.add_argument("--target", default=".")
    native_inspect.add_argument("--include-global-config", action="store_true")
    native_install = native_sub.add_parser("install", help="Preview or install native Invart hook/plugin config.")
    native_install.add_argument("--target", default=".")
    native_install.add_argument("--agent", choices=("claude-code", "codex", "opencode"), required=True)
    native_install.add_argument("--confirm", action="store_true")
    native_conformance = native_sub.add_parser("conformance", help="Hash and validate discovered native integration surfaces.")
    native_conformance.add_argument("--target", default=".")
    native_conformance.add_argument("--include-global-config", action="store_true")

    launcher = subparsers.add_parser("launcher", help="Preview, install, and verify Invart-managed launchers.")
    launcher.set_defaults(handler=handle_launcher)
    launcher_sub = launcher.add_subparsers(dest="launcher_command", required=True)
    for launcher_command in ("preview", "install", "verify"):
        launcher_parser = launcher_sub.add_parser(launcher_command, help=f"{launcher_command.title()} a managed launcher.")
        launcher_parser.add_argument("--target", default=".")
        launcher_parser.add_argument("--agent", choices=("claude-code", "codex", "gemini-cli", "cursor", "opencode", "openclaw", "hermes", "generic"), required=True)
        launcher_parser.add_argument("--launcher", choices=("shell",), default="shell")

    bridge = subparsers.add_parser("bridge", help="Native hook/plugin bridge commands.")
    bridge.set_defaults(handler=handle_bridge)
    bridge_sub = bridge.add_subparsers(dest="bridge_command", required=True)
    bridge_native = bridge_sub.add_parser("native", help="Normalize a native hook payload and return a native response.")
    bridge_native.add_argument("--agent", choices=("claude-code", "codex", "opencode", "generic"), required=True)
    bridge_native.add_argument("--event", required=True)
    bridge_conformance = bridge_sub.add_parser("conformance", help="Run native bridge response-shape conformance checks.")

    mcp = subparsers.add_parser("mcp", help="MCP broker and inspection commands.")
    mcp.set_defaults(handler=handle_mcp)
    mcp_sub = mcp.add_subparsers(dest="mcp_command", required=True)
    mcp_broker = mcp_sub.add_parser("broker-step", help="Run one transparent MCP broker step for a JSON message.")
    mcp_broker.add_argument("--message", required=True)
    mcp_stdio = mcp_sub.add_parser("broker-stdio", help="Run a transparent JSONL stdio broker with transcript capture.")
    mcp_stdio.add_argument("--input", required=True)
    mcp_stdio.add_argument("--output", required=True)
    mcp_stdio.add_argument("--transcript", required=True)

    coverage = subparsers.add_parser("coverage", help="Export coverage-aware proof reports.")
    coverage.set_defaults(handler=handle_coverage)
    coverage_sub = coverage.add_subparsers(dest="coverage_command", required=True)
    coverage_html = coverage_sub.add_parser("html", help="Export a coverage matrix HTML report from proof JSON.")
    coverage_html.add_argument("--proof", required=True)
    coverage_html.add_argument("--out", required=True)

    graph = subparsers.add_parser("graph", help="Export and query ledger-derived execution path graphs.")
    graph.set_defaults(handler=handle_graph)
    graph_sub = graph.add_subparsers(dest="graph_command", required=True)
    graph_export = graph_sub.add_parser("export", help="Export execution graph JSON.")
    graph_export.add_argument("--ledger", required=True)
    graph_export.add_argument("--out", required=True)
    graph_html = graph_sub.add_parser("html", help="Export execution graph HTML.")
    graph_html.add_argument("--ledger", required=True)
    graph_html.add_argument("--out", required=True)
    graph_query = graph_sub.add_parser("query", help="Query graph upstream or downstream from a node.")
    graph_query.add_argument("--ledger", required=True)
    graph_query.add_argument("--target", required=True)
    graph_query.add_argument("--direction", choices=("upstream", "downstream"), default="upstream")

    mediation = subparsers.add_parser("mediation", help="Inspect and resolve unified mediation records.")
    mediation.set_defaults(handler=handle_mediation)
    mediation_sub = mediation.add_subparsers(dest="mediation_command", required=True)
    mediation_inspect = mediation_sub.add_parser("inspect", help="Replay mediation events from a ledger.")
    mediation_inspect.add_argument("--ledger", required=True)
    mediation_resolve = mediation_sub.add_parser("resolve", help="Resolve a paused mediation item.")
    mediation_resolve.add_argument("--ledger", required=True)
    mediation_resolve.add_argument("--mediation", required=True)
    mediation_resolve.add_argument("--actor", required=True)
    mediation_resolve.add_argument("--status", choices=("approved", "rejected"), required=True)
    mediation_resolve.add_argument("--reason", required=True)
    mediation_replay = mediation_sub.add_parser("replay", help="Replay mediation records from a ledger.")
    mediation_replay.add_argument("--ledger", required=True)

    supervise = subparsers.add_parser("supervise", help="Run process-group supervision checks.")
    supervise.set_defaults(handler=handle_supervise)
    supervise_sub = supervise.add_subparsers(dest="supervise_command", required=True)
    supervise_run = supervise_sub.add_parser("run", help="Run a command under process-group supervision.")
    supervise_run.add_argument("--target", default=None)
    supervise_run.add_argument("cmd", nargs=argparse.REMAINDER)
