from __future__ import annotations

import argparse

from .product import handle_audit, handle_demo, handle_eval, handle_evidence, handle_experiment, handle_external_evidence, handle_release_candidate, handle_roadmap


def register_product_commands(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    eval_parser = subparsers.add_parser("eval", help="Run Invart effectiveness benchmarks.")
    eval_parser.set_defaults(handler=handle_eval)
    eval_sub = eval_parser.add_subparsers(dest="eval_command", required=True)
    eval_list = eval_sub.add_parser("list", help="List built-in benchmark suites.")
    eval_report = eval_sub.add_parser("report", help="Run a benchmark suite and write a JSON report.")
    eval_report.add_argument("--suite", default="full-product-readiness")
    eval_report.add_argument("--out", required=True)
    benchmark = eval_sub.add_parser("benchmark", help="Run a built-in benchmark suite through the runtime pipeline.")
    benchmark.add_argument("--suite", default="v0.2-semantic")
    benchmark.add_argument("--reviewer", choices=("heuristic", "llm"), default="heuristic")
    benchmark.add_argument("--policy-profile", choices=("balanced", "strict", "audit"), default="balanced")

    experiment = subparsers.add_parser("experiment", help="Run benchmark-derived LLM agent experiment suites.")
    experiment.set_defaults(handler=handle_experiment)
    experiment_sub = experiment.add_subparsers(dest="experiment_command", required=True)
    experiment_list = experiment_sub.add_parser("list", help="List benchmark experiment suites.")
    experiment_run = experiment_sub.add_parser("run", help="Run an experiment suite and write artifacts.")
    experiment_run.add_argument("--suite", default="control-plane-core")
    experiment_run.add_argument("--out-dir", required=True)
    experiment_report = experiment_sub.add_parser("report", help="Render an experiment run JSON as HTML.")
    experiment_report.add_argument("--run", required=True)
    experiment_report.add_argument("--out", required=True)
    experiment_validate = experiment_sub.add_parser("validate-fixtures", help="Validate benchmark-derived experiment fixture JSON files.")
    experiment_validate.add_argument("--root", default="benchmarks/experiments")
    experiment_paper = experiment_sub.add_parser("paper-suite", help="Generate the v0.39 paper-ready experiment bundle.")
    experiment_paper.add_argument("--out-dir", required=True)
    experiment_tables = experiment_sub.add_parser("paper-tables", help="Export v0.46 paper evidence tables from a paper suite JSON artifact.")
    experiment_tables.add_argument("--paper-suite", required=True)
    experiment_tables.add_argument("--out-dir", required=True)
    experiment_coverage = experiment_sub.add_parser("coverage-matrix", help="Generate the v0.47 same-action coverage mediation matrix.")
    experiment_coverage.add_argument("--out-dir", required=True)
    experiment_audit_reconstruction = experiment_sub.add_parser("audit-reconstruction", help="Generate the v0.48 audit reconstruction study artifacts.")
    experiment_audit_reconstruction.add_argument("--out-dir", required=True)
    experiment_reviewer = experiment_sub.add_parser("reviewer-ablation", help="Generate the v0.49 reviewer ablation and cost artifacts.")
    experiment_reviewer.add_argument("--out-dir", required=True)
    experiment_product_matrix = experiment_sub.add_parser("product-control-matrix", help="Generate the v0.50 product control matrix artifacts.")
    experiment_product_matrix.add_argument("--out-dir", required=True)

    evidence = subparsers.add_parser("evidence", help="Export and verify enterprise evidence bundles.")
    evidence.set_defaults(handler=handle_evidence)
    evidence_sub = evidence.add_subparsers(dest="evidence_command", required=True)
    evidence_export = evidence_sub.add_parser("export", help="Export a v0.27 evidence bundle from a ledger.")
    evidence_export.add_argument("--ledger", required=True)
    evidence_export.add_argument("--out-dir", required=True)
    evidence_export.add_argument("--profile", default=None)
    evidence_verify = evidence_sub.add_parser("verify", help="Verify an evidence bundle manifest.")
    evidence_verify.add_argument("--bundle", required=True)

    external_evidence = subparsers.add_parser("external-evidence", help="Import, attach, and verify external benchmark evidence manifests.")
    external_evidence.set_defaults(handler=handle_external_evidence)
    external_evidence_sub = external_evidence.add_subparsers(dest="external_evidence_command", required=True)
    external_import = external_evidence_sub.add_parser("import", help="Import a pinned external corpus snapshot.")
    external_import.add_argument("--snapshot", required=True)
    external_import.add_argument("--out-dir", required=True)
    external_attach = external_evidence_sub.add_parser("attach", help="Attach full SWE-Bench evidence artifacts.")
    external_attach.add_argument("--report", required=True)
    external_attach.add_argument("--instance-results", required=True)
    external_attach.add_argument("--predictions", required=True)
    external_attach.add_argument("--logs", required=True)
    external_attach.add_argument("--out-dir", required=True)
    external_attach.add_argument("--run-id", default="invart_full")
    external_attach.add_argument("--expected-total-instances", type=int, default=2294)
    external_attach.add_argument("--invart-mode", "--kappaski-mode", dest="invart_mode", choices=("raw", "plugin-only", "audit", "managed", "enforced"), default="managed")
    external_verify = external_evidence_sub.add_parser("verify", help="Verify an external evidence manifest.")
    external_verify.add_argument("--manifest", required=True)
    external_progressive = external_evidence_sub.add_parser("progressive", help="Run progressive sample validation across external evidence categories.")
    external_progressive.add_argument("--out-dir", required=True)
    external_progressive.add_argument("--stage", choices=("smoke", "sample", "scale"), default="smoke")
    external_progressive.add_argument("--category", action="append", choices=("public-risk-catalog", "external-corpus-snapshot", "swe-bench"), default=[])
    external_progressive.add_argument("--max-cases", type=int, default=None)
    external_progressive.add_argument("--public-risk-catalog", default=None)
    external_progressive.add_argument("--snapshot", default=None)
    external_progressive.add_argument("--swe-report", default=None)
    external_progressive.add_argument("--swe-instance-results", default=None)
    external_progressive.add_argument("--swe-predictions", default=None)
    external_progressive.add_argument("--swe-logs", default=None)
    external_progressive.add_argument("--swe-run-id", default="invart_progressive_sample")

    audit = subparsers.add_parser("audit", help="Generate audit reports from runtime evidence.")
    audit.set_defaults(handler=handle_audit)
    audit_sub = audit.add_subparsers(dest="audit_command", required=True)
    audit_report = audit_sub.add_parser("report", help="Export audit JSON/HTML through an evidence bundle.")
    audit_report.add_argument("--ledger", required=True)
    audit_report.add_argument("--out-dir", required=True)


    roadmap = subparsers.add_parser("roadmap", help="Inspect implementation coverage against the roadmap.")
    roadmap.set_defaults(handler=handle_roadmap)
    roadmap_sub = roadmap.add_subparsers(dest="roadmap_command", required=True)
    roadmap_status = roadmap_sub.add_parser("status", help="Show roadmap implementation coverage and gaps.")
    roadmap_status.add_argument("--require-full", action="store_true")
    roadmap_status.add_argument("--require-external-validation", action="store_true", help="Fail if optional external/live benchmark validation has not been run.")

    demo = subparsers.add_parser("demo", help="Generate packaged product demos and audit artifacts.")
    demo.set_defaults(handler=handle_demo)
    demo_sub = demo.add_subparsers(dest="demo_command", required=True)
    demo_enterprise = demo_sub.add_parser("enterprise-audit", help="Generate the v0.14 enterprise security audit demo.")
    demo_enterprise.add_argument("--out-dir", required=True)
    demo_enterprise.add_argument("--mode", choices=("scripted", "live-adapter"), default="scripted")
    demo_pre_v1 = demo_sub.add_parser("pre-v1-control-plane", help="Generate the v0.24 pre-v1 control-plane demo package.")
    demo_pre_v1.add_argument("--out-dir", required=True)
    demo_real_world = demo_sub.add_parser("real-world-risk-cases", help="Generate public-source risk mapping plus before/during/after Invart demo artifacts.")
    demo_real_world.add_argument("--out-dir", required=True)
    demo_container_case = demo_sub.add_parser("container-risk-case", help="Generate one container-isolated risk demo case artifact bundle.")
    demo_container_case.add_argument("--case", required=True, choices=("unfriendly-skill", "secret-egress", "unsafe-delete"))
    demo_container_case.add_argument("--out-dir", required=True)
    demo_container_suite = demo_sub.add_parser("container-risk-suite", help="Generate or collect the containerized risk demo suite.")
    demo_container_suite.add_argument("--out-dir", required=True)
    demo_container_suite.add_argument("--collect-existing", action="store_true", help="Collect existing per-case container outputs instead of running cases locally.")
    demo_final = demo_sub.add_parser("pre-1.0-final", help="Generate the pre-1.0 final demo entrypoint and linked artifacts.")
    demo_final.add_argument("--out-dir", required=True)
    demo_final.add_argument("--external-evidence", default=None)
    demo_signoff = demo_sub.add_parser("signoff", help="Record ledger-backed enterprise audit signoff.")
    demo_signoff.add_argument("--ledger", required=True)
    demo_signoff.add_argument("--actor", required=True)
    demo_signoff.add_argument("--status", choices=("approved", "rejected", "needs_followup"), required=True)
    demo_signoff.add_argument("--reason", required=True)
    demo_signoff.add_argument("--report", default=None)

    for rc_name in ("release-candidate", "rc"):
        rc_parser = subparsers.add_parser(rc_name, help="Run the pre-1.0 release-candidate readiness gate.")
        rc_parser.set_defaults(handler=handle_release_candidate)
        rc_sub = rc_parser.add_subparsers(dest="rc_command", required=True)
        rc_verify = rc_sub.add_parser("verify", help="Verify pytest, roadmap, benchmarks, docs, and artifacts.")
        rc_verify.add_argument("--out-dir", required=True)
        rc_verify.add_argument("--skip-pytest", action="store_true")
        rc_verify.add_argument("--final", action="store_true")
        rc_verify.add_argument("--require-external-validation", action="store_true")
        rc_verify.add_argument("--external-evidence", default=None)
        rc_verify.add_argument("--paper", action="store_true", help="Run the separate v0.51 research-readiness gate after product RC checks.")
        rc_verify.add_argument("--paper-tables", default=None)
        rc_verify.add_argument("--coverage", default=None)
        rc_verify.add_argument("--reviewer", default=None)
        rc_verify.add_argument("--audit", default=None)
        rc_verify.add_argument("--product-matrix", default=None)
